Comment out test job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -51,53 +51,53 @@ jobs:
       - name: Run Compile
         run: ./gradlew assembleDebug
 
-  test:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - name: set up JDK 11
-        uses: actions/setup-java@v2
-        with:
-          distribution: 'zulu'
-          java-version: '11'
-
-      - name: Copy CI gradle.properties
-        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
-
-      # Gradleのキャッシュ復元
-      - uses: actions/cache@v2
-        with:
-          path: ~/.gradle/caches
-          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
-          restore-keys: |
-            ${{ runner.os }}-gradle-
-
-      # テスト
-      - name: Test with Gradle
-        run: ./gradlew test --stacktrace
-
-      # コードカバレッジをJaCoCo形式で取得
-      - name: Get code coverage for JaCoCo
-        run: ./gradlew createDebugCoverageReport --stacktrace
-
-      # コードカバレッジをCodecovへアップロード
-      - name: Upload code coverage to Codecov
-        run: bash <(curl -s https://codecov.io/bash)
-        env:
-          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
-
-      # テスト結果とコードカバレッジのアップロード
-      - name: Upload test results and code coverage Artifact
-        uses: actions/upload-artifact@v2
-        if: success() || failure()
-        with:
-          name: results
-          path: |
-            **/build/reports/tests/**/*
-            **/build/reports/test-results/**/*
-            **/build/reports/jacoco/**/*
-          if-no-files-found: warn
-          retention-days: 14
+#  test:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v2
+#      - name: set up JDK 11
+#        uses: actions/setup-java@v2
+#        with:
+#          distribution: 'zulu'
+#          java-version: '11'
+#
+#      - name: Copy CI gradle.properties
+#        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
+#
+#      # Gradleのキャッシュ復元
+#      - uses: actions/cache@v2
+#        with:
+#          path: ~/.gradle/caches
+#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
+#          restore-keys: |
+#            ${{ runner.os }}-gradle-
+#
+#      # テスト
+#      - name: Test with Gradle
+#        run: ./gradlew test --stacktrace
+#
+#      # コードカバレッジをJaCoCo形式で取得
+#      - name: Get code coverage for JaCoCo
+#        run: ./gradlew createDebugCoverageReport --stacktrace
+#
+#      # コードカバレッジをCodecovへアップロード
+#      - name: Upload code coverage to Codecov
+#        run: bash <(curl -s https://codecov.io/bash)
+#        env:
+#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+#
+#      # テスト結果とコードカバレッジのアップロード
+#      - name: Upload test results and code coverage Artifact
+#        uses: actions/upload-artifact@v2
+#        if: success() || failure()
+#        with:
+#          name: results
+#          path: |
+#            **/build/reports/tests/**/*
+#            **/build/reports/test-results/**/*
+#            **/build/reports/jacoco/**/*
+#          if-no-files-found: warn
+#          retention-days: 14
 
   lint:
     runs-on: ubuntu-latest
